services:
    _defaults:
        autoconfigure: true
        public: false
        autowire: false

    Support\:
        exclude: '../support/Testing/*'
        resource: '../support/*'

    Product\:
        resource: '../src/*'
